stages:
  generate:
    cmd: python src/gen.py
    deps:
      - src/create.py
      - src/generators.py
    outs:
      - data/dists.csv
      - data/train.csv
      - data/val.csv
      - data/test.csv
    params:
      - seed
      - generate
    plots:
      - evaluation/train_stripplot.png
      - evaluation/val_stripplot.png
      - evaluation/test_stripplot.png
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - src/models.py
      - data/train.csv
      - data/val.csv
    outs:
      - models/monte_carlo_dropout.json
      - models/monte_carlo_dropout
    params:
      - train
    metrics:
      - metrics/train.json
      - metrics/calib.json
  eval:
    cmd: python src/eval.py
    deps:
      - src/eval.py
      - src/models.py
      - data/test.csv
      - data/dists.csv
      - models/monte_carlo_dropout
      - models/monte_carlo_dropout.json
    params:
      - eval
    plots:
      - evaluation/vs_test.png
      - evaluation/vs_underlying.png
